from __future__ import annotations

import typing as _typing
import builtins


import enum

import folly.iobuf as _fbthrift_iobuf
import apache.thrift.metadata.thrift_abstract_types as _fbthrift_python_abstract_types
import thrift.python.types as _fbthrift_python_types
import thrift.python.exceptions as _fbthrift_python_exceptions

from apache.thrift.metadata.thrift_enums import (
    ThriftPrimitiveType as _fbthrift_ThriftPrimitiveType,
)
ThriftPrimitiveType = _fbthrift_ThriftPrimitiveType


@_typing.final
class ThriftConstValuePair(_fbthrift_python_types.Struct, _fbthrift_python_abstract_types.ThriftConstValuePair):
    key: _typing.Final[_fbthrift_ThriftConstValue] = ...
    value: _typing.Final[_fbthrift_ThriftConstValue] = ...
    def __init__(
        self, *,
        key: _typing.Optional[_fbthrift_ThriftConstValue]=...,
        value: _typing.Optional[_fbthrift_ThriftConstValue]=...
    ) -> None: no_effects()

    def __call__(
        self, *,
        key: _typing.Optional[_fbthrift_ThriftConstValue]=...,
        value: _typing.Optional[_fbthrift_ThriftConstValue]=...
    ) -> _typing.Self: ...
    def __iter__(self) -> _typing.Iterator[_typing.Tuple[builtins.str, _typing.Union[_fbthrift_ThriftConstValue, _fbthrift_ThriftConstValue]]]: ...
    def _to_python(self) -> _typing.Self: ...
    def _to_mutable_python(self) -> "apache.thrift.metadata.thrift_mutable_types.ThriftConstValuePair": ...  # type: ignore
    def _to_py3(self) -> "apache.thrift.metadata.types.ThriftConstValuePair": ...  # type: ignore
    def _to_py_deprecated(self) -> "apache.thrift.metadata.ttypes.ThriftConstValuePair": ...  # type: ignore
_fbthrift_ThriftConstValuePair = ThriftConstValuePair

@_typing.final
class ThriftConstValue(_fbthrift_python_types.Union, _fbthrift_python_abstract_types.ThriftConstValue):
    cv_bool: _typing.Final[builtins.bool] = ...
    cv_integer: _typing.Final[builtins.int] = ...
    cv_double: _typing.Final[builtins.float] = ...
    cv_string: _typing.Final[builtins.str] = ...
    cv_map: _typing.Final[_typing.Sequence[_fbthrift_ThriftConstValuePair]] = ...
    cv_list: _typing.Final[_typing.Sequence[_fbthrift_ThriftConstValue]] = ...
    cv_struct: _typing.Final[_fbthrift_ThriftConstStruct] = ...
    def __init__(
        self, *,
        cv_bool: _typing.Optional[builtins.bool]=...,
        cv_integer: _typing.Optional[builtins.int]=...,
        cv_double: _typing.Optional[builtins.float]=...,
        cv_string: _typing.Optional[builtins.str]=...,
        cv_map: _typing.Optional[_typing.Sequence[_fbthrift_ThriftConstValuePair]]=...,
        cv_list: _typing.Optional[_typing.Sequence[_fbthrift_ThriftConstValue]]=...,
        cv_struct: _typing.Optional[_fbthrift_ThriftConstStruct]=...
    ) -> None: no_effects()


    class Type(enum.Enum):
        EMPTY: ThriftConstValue.Type = ...
        cv_bool: ThriftConstValue.Type = ...
        cv_integer: ThriftConstValue.Type = ...
        cv_double: ThriftConstValue.Type = ...
        cv_string: ThriftConstValue.Type = ...
        cv_map: ThriftConstValue.Type = ...
        cv_list: ThriftConstValue.Type = ...
        cv_struct: ThriftConstValue.Type = ...

    class FbThriftUnionFieldEnum(enum.Enum):
        EMPTY: ThriftConstValue.FbThriftUnionFieldEnum = ...
        cv_bool: ThriftConstValue.FbThriftUnionFieldEnum = ...
        cv_integer: ThriftConstValue.FbThriftUnionFieldEnum = ...
        cv_double: ThriftConstValue.FbThriftUnionFieldEnum = ...
        cv_string: ThriftConstValue.FbThriftUnionFieldEnum = ...
        cv_map: ThriftConstValue.FbThriftUnionFieldEnum = ...
        cv_list: ThriftConstValue.FbThriftUnionFieldEnum = ...
        cv_struct: ThriftConstValue.FbThriftUnionFieldEnum = ...

    fbthrift_current_value: _typing.Final[_typing.Union[None, builtins.bool, builtins.int, builtins.float, builtins.str, _typing.Sequence[_fbthrift_ThriftConstValuePair], _typing.Sequence[_fbthrift_ThriftConstValue], _fbthrift_ThriftConstStruct]]
    fbthrift_current_field: _typing.Final[FbThriftUnionFieldEnum]
    @classmethod
    def fromValue(cls, value: _typing.Union[None, builtins.bool, builtins.int, builtins.float, builtins.str, _typing.Sequence[_fbthrift_ThriftConstValuePair], _typing.Sequence[_fbthrift_ThriftConstValue], _fbthrift_ThriftConstStruct]) -> ThriftConstValue: ...
    value: _typing.Final[_typing.Union[None, builtins.bool, builtins.int, builtins.float, builtins.str, _typing.Sequence[_fbthrift_ThriftConstValuePair], _typing.Sequence[_fbthrift_ThriftConstValue], _fbthrift_ThriftConstStruct]]
    type: _typing.Final[Type]
    def get_type(self) -> Type: ...
    def _to_python(self) -> _typing.Self: ...
    def _to_mutable_python(self) -> "apache.thrift.metadata.thrift_mutable_types.ThriftConstValue": ...  # type: ignore
    def _to_py3(self) -> "apache.thrift.metadata.types.ThriftConstValue": ...  # type: ignore
    def _to_py_deprecated(self) -> "apache.thrift.metadata.ttypes.ThriftConstValue": ...  # type: ignore
_fbthrift_ThriftConstValue = ThriftConstValue

@_typing.final
class ThriftConstStruct(_fbthrift_python_types.Struct, _fbthrift_python_abstract_types.ThriftConstStruct):
    type: _typing.Final[_fbthrift_ThriftStructType] = ...
    fields: _typing.Final[_typing.Mapping[builtins.str, _fbthrift_ThriftConstValue]] = ...
    def __init__(
        self, *,
        type: _typing.Optional[_fbthrift_ThriftStructType]=...,
        fields: _typing.Optional[_typing.Mapping[builtins.str, _fbthrift_ThriftConstValue]]=...
    ) -> None: no_effects()

    def __call__(
        self, *,
        type: _typing.Optional[_fbthrift_ThriftStructType]=...,
        fields: _typing.Optional[_typing.Mapping[builtins.str, _fbthrift_ThriftConstValue]]=...
    ) -> _typing.Self: ...
    def __iter__(self) -> _typing.Iterator[_typing.Tuple[builtins.str, _typing.Union[_fbthrift_ThriftStructType, _typing.Mapping[builtins.str, _fbthrift_ThriftConstValue]]]]: ...
    def _to_python(self) -> _typing.Self: ...
    def _to_mutable_python(self) -> "apache.thrift.metadata.thrift_mutable_types.ThriftConstStruct": ...  # type: ignore
    def _to_py3(self) -> "apache.thrift.metadata.types.ThriftConstStruct": ...  # type: ignore
    def _to_py_deprecated(self) -> "apache.thrift.metadata.ttypes.ThriftConstStruct": ...  # type: ignore
_fbthrift_ThriftConstStruct = ThriftConstStruct

@_typing.final
class ThriftListType(_fbthrift_python_types.Struct, _fbthrift_python_abstract_types.ThriftListType):
    valueType: _typing.Final[_typing.Optional[_fbthrift_ThriftType]] = ...
    def __init__(
        self, *,
        valueType: _typing.Optional[_fbthrift_ThriftType]=...
    ) -> None: no_effects()

    def __call__(
        self, *,
        valueType: _typing.Optional[_fbthrift_ThriftType]=...
    ) -> _typing.Self: ...
    def __iter__(self) -> _typing.Iterator[_typing.Tuple[builtins.str, _typing.Union[_fbthrift_ThriftType]]]: ...
    def _to_python(self) -> _typing.Self: ...
    def _to_mutable_python(self) -> "apache.thrift.metadata.thrift_mutable_types.ThriftListType": ...  # type: ignore
    def _to_py3(self) -> "apache.thrift.metadata.types.ThriftListType": ...  # type: ignore
    def _to_py_deprecated(self) -> "apache.thrift.metadata.ttypes.ThriftListType": ...  # type: ignore
_fbthrift_ThriftListType = ThriftListType

@_typing.final
class ThriftSetType(_fbthrift_python_types.Struct, _fbthrift_python_abstract_types.ThriftSetType):
    valueType: _typing.Final[_typing.Optional[_fbthrift_ThriftType]] = ...
    def __init__(
        self, *,
        valueType: _typing.Optional[_fbthrift_ThriftType]=...
    ) -> None: no_effects()

    def __call__(
        self, *,
        valueType: _typing.Optional[_fbthrift_ThriftType]=...
    ) -> _typing.Self: ...
    def __iter__(self) -> _typing.Iterator[_typing.Tuple[builtins.str, _typing.Union[_fbthrift_ThriftType]]]: ...
    def _to_python(self) -> _typing.Self: ...
    def _to_mutable_python(self) -> "apache.thrift.metadata.thrift_mutable_types.ThriftSetType": ...  # type: ignore
    def _to_py3(self) -> "apache.thrift.metadata.types.ThriftSetType": ...  # type: ignore
    def _to_py_deprecated(self) -> "apache.thrift.metadata.ttypes.ThriftSetType": ...  # type: ignore
_fbthrift_ThriftSetType = ThriftSetType

@_typing.final
class ThriftMapType(_fbthrift_python_types.Struct, _fbthrift_python_abstract_types.ThriftMapType):
    keyType: _typing.Final[_typing.Optional[_fbthrift_ThriftType]] = ...
    valueType: _typing.Final[_typing.Optional[_fbthrift_ThriftType]] = ...
    def __init__(
        self, *,
        keyType: _typing.Optional[_fbthrift_ThriftType]=...,
        valueType: _typing.Optional[_fbthrift_ThriftType]=...
    ) -> None: no_effects()

    def __call__(
        self, *,
        keyType: _typing.Optional[_fbthrift_ThriftType]=...,
        valueType: _typing.Optional[_fbthrift_ThriftType]=...
    ) -> _typing.Self: ...
    def __iter__(self) -> _typing.Iterator[_typing.Tuple[builtins.str, _typing.Union[_fbthrift_ThriftType, _fbthrift_ThriftType]]]: ...
    def _to_python(self) -> _typing.Self: ...
    def _to_mutable_python(self) -> "apache.thrift.metadata.thrift_mutable_types.ThriftMapType": ...  # type: ignore
    def _to_py3(self) -> "apache.thrift.metadata.types.ThriftMapType": ...  # type: ignore
    def _to_py_deprecated(self) -> "apache.thrift.metadata.ttypes.ThriftMapType": ...  # type: ignore
_fbthrift_ThriftMapType = ThriftMapType

@_typing.final
class ThriftEnumType(_fbthrift_python_types.Struct, _fbthrift_python_abstract_types.ThriftEnumType):
    name: _typing.Final[builtins.str] = ...
    def __init__(
        self, *,
        name: _typing.Optional[builtins.str]=...
    ) -> None: no_effects()

    def __call__(
        self, *,
        name: _typing.Optional[builtins.str]=...
    ) -> _typing.Self: ...
    def __iter__(self) -> _typing.Iterator[_typing.Tuple[builtins.str, _typing.Union[builtins.str]]]: ...
    def _to_python(self) -> _typing.Self: ...
    def _to_mutable_python(self) -> "apache.thrift.metadata.thrift_mutable_types.ThriftEnumType": ...  # type: ignore
    def _to_py3(self) -> "apache.thrift.metadata.types.ThriftEnumType": ...  # type: ignore
    def _to_py_deprecated(self) -> "apache.thrift.metadata.ttypes.ThriftEnumType": ...  # type: ignore
_fbthrift_ThriftEnumType = ThriftEnumType

@_typing.final
class ThriftStructType(_fbthrift_python_types.Struct, _fbthrift_python_abstract_types.ThriftStructType):
    name: _typing.Final[builtins.str] = ...
    def __init__(
        self, *,
        name: _typing.Optional[builtins.str]=...
    ) -> None: no_effects()

    def __call__(
        self, *,
        name: _typing.Optional[builtins.str]=...
    ) -> _typing.Self: ...
    def __iter__(self) -> _typing.Iterator[_typing.Tuple[builtins.str, _typing.Union[builtins.str]]]: ...
    def _to_python(self) -> _typing.Self: ...
    def _to_mutable_python(self) -> "apache.thrift.metadata.thrift_mutable_types.ThriftStructType": ...  # type: ignore
    def _to_py3(self) -> "apache.thrift.metadata.types.ThriftStructType": ...  # type: ignore
    def _to_py_deprecated(self) -> "apache.thrift.metadata.ttypes.ThriftStructType": ...  # type: ignore
_fbthrift_ThriftStructType = ThriftStructType

@_typing.final
class ThriftUnionType(_fbthrift_python_types.Struct, _fbthrift_python_abstract_types.ThriftUnionType):
    name: _typing.Final[builtins.str] = ...
    def __init__(
        self, *,
        name: _typing.Optional[builtins.str]=...
    ) -> None: no_effects()

    def __call__(
        self, *,
        name: _typing.Optional[builtins.str]=...
    ) -> _typing.Self: ...
    def __iter__(self) -> _typing.Iterator[_typing.Tuple[builtins.str, _typing.Union[builtins.str]]]: ...
    def _to_python(self) -> _typing.Self: ...
    def _to_mutable_python(self) -> "apache.thrift.metadata.thrift_mutable_types.ThriftUnionType": ...  # type: ignore
    def _to_py3(self) -> "apache.thrift.metadata.types.ThriftUnionType": ...  # type: ignore
    def _to_py_deprecated(self) -> "apache.thrift.metadata.ttypes.ThriftUnionType": ...  # type: ignore
_fbthrift_ThriftUnionType = ThriftUnionType

@_typing.final
class ThriftTypedefType(_fbthrift_python_types.Struct, _fbthrift_python_abstract_types.ThriftTypedefType):
    name: _typing.Final[builtins.str] = ...
    underlyingType: _typing.Final[_typing.Optional[_fbthrift_ThriftType]] = ...
    structured_annotations: _typing.Final[_typing.Sequence[_fbthrift_ThriftConstStruct]] = ...
    def __init__(
        self, *,
        name: _typing.Optional[builtins.str]=...,
        underlyingType: _typing.Optional[_fbthrift_ThriftType]=...,
        structured_annotations: _typing.Optional[_typing.Sequence[_fbthrift_ThriftConstStruct]]=...
    ) -> None: no_effects()

    def __call__(
        self, *,
        name: _typing.Optional[builtins.str]=...,
        underlyingType: _typing.Optional[_fbthrift_ThriftType]=...,
        structured_annotations: _typing.Optional[_typing.Sequence[_fbthrift_ThriftConstStruct]]=...
    ) -> _typing.Self: ...
    def __iter__(self) -> _typing.Iterator[_typing.Tuple[builtins.str, _typing.Union[builtins.str, _fbthrift_ThriftType, _typing.Sequence[_fbthrift_ThriftConstStruct]]]]: ...
    def _to_python(self) -> _typing.Self: ...
    def _to_mutable_python(self) -> "apache.thrift.metadata.thrift_mutable_types.ThriftTypedefType": ...  # type: ignore
    def _to_py3(self) -> "apache.thrift.metadata.types.ThriftTypedefType": ...  # type: ignore
    def _to_py_deprecated(self) -> "apache.thrift.metadata.ttypes.ThriftTypedefType": ...  # type: ignore
_fbthrift_ThriftTypedefType = ThriftTypedefType

@_typing.final
class ThriftStreamType(_fbthrift_python_types.Struct, _fbthrift_python_abstract_types.ThriftStreamType):
    elemType: _typing.Final[_typing.Optional[_fbthrift_ThriftType]] = ...
    initialResponseType: _typing.Final[_typing.Optional[_fbthrift_ThriftType]] = ...
    def __init__(
        self, *,
        elemType: _typing.Optional[_fbthrift_ThriftType]=...,
        initialResponseType: _typing.Optional[_fbthrift_ThriftType]=...
    ) -> None: no_effects()

    def __call__(
        self, *,
        elemType: _typing.Optional[_fbthrift_ThriftType]=...,
        initialResponseType: _typing.Optional[_fbthrift_ThriftType]=...
    ) -> _typing.Self: ...
    def __iter__(self) -> _typing.Iterator[_typing.Tuple[builtins.str, _typing.Union[_fbthrift_ThriftType, _fbthrift_ThriftType]]]: ...
    def _to_python(self) -> _typing.Self: ...
    def _to_mutable_python(self) -> "apache.thrift.metadata.thrift_mutable_types.ThriftStreamType": ...  # type: ignore
    def _to_py3(self) -> "apache.thrift.metadata.types.ThriftStreamType": ...  # type: ignore
    def _to_py_deprecated(self) -> "apache.thrift.metadata.ttypes.ThriftStreamType": ...  # type: ignore
_fbthrift_ThriftStreamType = ThriftStreamType

@_typing.final
class ThriftSinkType(_fbthrift_python_types.Struct, _fbthrift_python_abstract_types.ThriftSinkType):
    elemType: _typing.Final[_typing.Optional[_fbthrift_ThriftType]] = ...
    finalResponseType: _typing.Final[_typing.Optional[_fbthrift_ThriftType]] = ...
    initialResponseType: _typing.Final[_typing.Optional[_fbthrift_ThriftType]] = ...
    def __init__(
        self, *,
        elemType: _typing.Optional[_fbthrift_ThriftType]=...,
        finalResponseType: _typing.Optional[_fbthrift_ThriftType]=...,
        initialResponseType: _typing.Optional[_fbthrift_ThriftType]=...
    ) -> None: no_effects()

    def __call__(
        self, *,
        elemType: _typing.Optional[_fbthrift_ThriftType]=...,
        finalResponseType: _typing.Optional[_fbthrift_ThriftType]=...,
        initialResponseType: _typing.Optional[_fbthrift_ThriftType]=...
    ) -> _typing.Self: ...
    def __iter__(self) -> _typing.Iterator[_typing.Tuple[builtins.str, _typing.Union[_fbthrift_ThriftType, _fbthrift_ThriftType, _fbthrift_ThriftType]]]: ...
    def _to_python(self) -> _typing.Self: ...
    def _to_mutable_python(self) -> "apache.thrift.metadata.thrift_mutable_types.ThriftSinkType": ...  # type: ignore
    def _to_py3(self) -> "apache.thrift.metadata.types.ThriftSinkType": ...  # type: ignore
    def _to_py_deprecated(self) -> "apache.thrift.metadata.ttypes.ThriftSinkType": ...  # type: ignore
_fbthrift_ThriftSinkType = ThriftSinkType

@_typing.final
class ThriftType(_fbthrift_python_types.Union, _fbthrift_python_abstract_types.ThriftType):
    t_primitive: _typing.Final[_fbthrift_ThriftPrimitiveType] = ...
    t_list: _typing.Final[_fbthrift_ThriftListType] = ...
    t_set: _typing.Final[_fbthrift_ThriftSetType] = ...
    t_map: _typing.Final[_fbthrift_ThriftMapType] = ...
    t_enum: _typing.Final[_fbthrift_ThriftEnumType] = ...
    t_struct: _typing.Final[_fbthrift_ThriftStructType] = ...
    t_union: _typing.Final[_fbthrift_ThriftUnionType] = ...
    t_typedef: _typing.Final[_fbthrift_ThriftTypedefType] = ...
    t_stream: _typing.Final[_fbthrift_ThriftStreamType] = ...
    t_sink: _typing.Final[_fbthrift_ThriftSinkType] = ...
    def __init__(
        self, *,
        t_primitive: _typing.Optional[_fbthrift_ThriftPrimitiveType]=...,
        t_list: _typing.Optional[_fbthrift_ThriftListType]=...,
        t_set: _typing.Optional[_fbthrift_ThriftSetType]=...,
        t_map: _typing.Optional[_fbthrift_ThriftMapType]=...,
        t_enum: _typing.Optional[_fbthrift_ThriftEnumType]=...,
        t_struct: _typing.Optional[_fbthrift_ThriftStructType]=...,
        t_union: _typing.Optional[_fbthrift_ThriftUnionType]=...,
        t_typedef: _typing.Optional[_fbthrift_ThriftTypedefType]=...,
        t_stream: _typing.Optional[_fbthrift_ThriftStreamType]=...,
        t_sink: _typing.Optional[_fbthrift_ThriftSinkType]=...
    ) -> None: no_effects()


    class Type(enum.Enum):
        EMPTY: ThriftType.Type = ...
        t_primitive: ThriftType.Type = ...
        t_list: ThriftType.Type = ...
        t_set: ThriftType.Type = ...
        t_map: ThriftType.Type = ...
        t_enum: ThriftType.Type = ...
        t_struct: ThriftType.Type = ...
        t_union: ThriftType.Type = ...
        t_typedef: ThriftType.Type = ...
        t_stream: ThriftType.Type = ...
        t_sink: ThriftType.Type = ...

    class FbThriftUnionFieldEnum(enum.Enum):
        EMPTY: ThriftType.FbThriftUnionFieldEnum = ...
        t_primitive: ThriftType.FbThriftUnionFieldEnum = ...
        t_list: ThriftType.FbThriftUnionFieldEnum = ...
        t_set: ThriftType.FbThriftUnionFieldEnum = ...
        t_map: ThriftType.FbThriftUnionFieldEnum = ...
        t_enum: ThriftType.FbThriftUnionFieldEnum = ...
        t_struct: ThriftType.FbThriftUnionFieldEnum = ...
        t_union: ThriftType.FbThriftUnionFieldEnum = ...
        t_typedef: ThriftType.FbThriftUnionFieldEnum = ...
        t_stream: ThriftType.FbThriftUnionFieldEnum = ...
        t_sink: ThriftType.FbThriftUnionFieldEnum = ...

    fbthrift_current_value: _typing.Final[_typing.Union[None, _fbthrift_ThriftPrimitiveType, _fbthrift_ThriftListType, _fbthrift_ThriftSetType, _fbthrift_ThriftMapType, _fbthrift_ThriftEnumType, _fbthrift_ThriftStructType, _fbthrift_ThriftUnionType, _fbthrift_ThriftTypedefType, _fbthrift_ThriftStreamType, _fbthrift_ThriftSinkType]]
    fbthrift_current_field: _typing.Final[FbThriftUnionFieldEnum]
    @classmethod
    def fromValue(cls, value: _typing.Union[None, _fbthrift_ThriftPrimitiveType, _fbthrift_ThriftListType, _fbthrift_ThriftSetType, _fbthrift_ThriftMapType, _fbthrift_ThriftEnumType, _fbthrift_ThriftStructType, _fbthrift_ThriftUnionType, _fbthrift_ThriftTypedefType, _fbthrift_ThriftStreamType, _fbthrift_ThriftSinkType]) -> ThriftType: ...
    value: _typing.Final[_typing.Union[None, _fbthrift_ThriftPrimitiveType, _fbthrift_ThriftListType, _fbthrift_ThriftSetType, _fbthrift_ThriftMapType, _fbthrift_ThriftEnumType, _fbthrift_ThriftStructType, _fbthrift_ThriftUnionType, _fbthrift_ThriftTypedefType, _fbthrift_ThriftStreamType, _fbthrift_ThriftSinkType]]
    type: _typing.Final[Type]
    def get_type(self) -> Type: ...
    def _to_python(self) -> _typing.Self: ...
    def _to_mutable_python(self) -> "apache.thrift.metadata.thrift_mutable_types.ThriftType": ...  # type: ignore
    def _to_py3(self) -> "apache.thrift.metadata.types.ThriftType": ...  # type: ignore
    def _to_py_deprecated(self) -> "apache.thrift.metadata.ttypes.ThriftType": ...  # type: ignore
_fbthrift_ThriftType = ThriftType

@_typing.final
class ThriftEnum(_fbthrift_python_types.Struct, _fbthrift_python_abstract_types.ThriftEnum):
    name: _typing.Final[builtins.str] = ...
    elements: _typing.Final[_typing.Mapping[builtins.int, builtins.str]] = ...
    structured_annotations: _typing.Final[_typing.Sequence[_fbthrift_ThriftConstStruct]] = ...
    def __init__(
        self, *,
        name: _typing.Optional[builtins.str]=...,
        elements: _typing.Optional[_typing.Mapping[builtins.int, builtins.str]]=...,
        structured_annotations: _typing.Optional[_typing.Sequence[_fbthrift_ThriftConstStruct]]=...
    ) -> None: no_effects()

    def __call__(
        self, *,
        name: _typing.Optional[builtins.str]=...,
        elements: _typing.Optional[_typing.Mapping[builtins.int, builtins.str]]=...,
        structured_annotations: _typing.Optional[_typing.Sequence[_fbthrift_ThriftConstStruct]]=...
    ) -> _typing.Self: ...
    def __iter__(self) -> _typing.Iterator[_typing.Tuple[builtins.str, _typing.Union[builtins.str, _typing.Mapping[builtins.int, builtins.str], _typing.Sequence[_fbthrift_ThriftConstStruct]]]]: ...
    def _to_python(self) -> _typing.Self: ...
    def _to_mutable_python(self) -> "apache.thrift.metadata.thrift_mutable_types.ThriftEnum": ...  # type: ignore
    def _to_py3(self) -> "apache.thrift.metadata.types.ThriftEnum": ...  # type: ignore
    def _to_py_deprecated(self) -> "apache.thrift.metadata.ttypes.ThriftEnum": ...  # type: ignore
_fbthrift_ThriftEnum = ThriftEnum

@_typing.final
class ThriftField(_fbthrift_python_types.Struct, _fbthrift_python_abstract_types.ThriftField):
    id: _typing.Final[builtins.int] = ...
    type: _typing.Final[_fbthrift_ThriftType] = ...
    name: _typing.Final[builtins.str] = ...
    is_optional: _typing.Final[builtins.bool] = ...
    structured_annotations: _typing.Final[_typing.Sequence[_fbthrift_ThriftConstStruct]] = ...
    unstructured_annotations: _typing.Final[_typing.Optional[_typing.Mapping[builtins.str, builtins.str]]] = ...
    def __init__(
        self, *,
        id: _typing.Optional[builtins.int]=...,
        type: _typing.Optional[_fbthrift_ThriftType]=...,
        name: _typing.Optional[builtins.str]=...,
        is_optional: _typing.Optional[builtins.bool]=...,
        structured_annotations: _typing.Optional[_typing.Sequence[_fbthrift_ThriftConstStruct]]=...,
        unstructured_annotations: _typing.Optional[_typing.Mapping[builtins.str, builtins.str]]=...
    ) -> None: no_effects()

    def __call__(
        self, *,
        id: _typing.Optional[builtins.int]=...,
        type: _typing.Optional[_fbthrift_ThriftType]=...,
        name: _typing.Optional[builtins.str]=...,
        is_optional: _typing.Optional[builtins.bool]=...,
        structured_annotations: _typing.Optional[_typing.Sequence[_fbthrift_ThriftConstStruct]]=...,
        unstructured_annotations: _typing.Optional[_typing.Mapping[builtins.str, builtins.str]]=...
    ) -> _typing.Self: ...
    def __iter__(self) -> _typing.Iterator[_typing.Tuple[builtins.str, _typing.Union[builtins.int, _fbthrift_ThriftType, builtins.str, builtins.bool, _typing.Sequence[_fbthrift_ThriftConstStruct], _typing.Mapping[builtins.str, builtins.str]]]]: ...
    def _to_python(self) -> _typing.Self: ...
    def _to_mutable_python(self) -> "apache.thrift.metadata.thrift_mutable_types.ThriftField": ...  # type: ignore
    def _to_py3(self) -> "apache.thrift.metadata.types.ThriftField": ...  # type: ignore
    def _to_py_deprecated(self) -> "apache.thrift.metadata.ttypes.ThriftField": ...  # type: ignore
_fbthrift_ThriftField = ThriftField

@_typing.final
class ThriftStruct(_fbthrift_python_types.Struct, _fbthrift_python_abstract_types.ThriftStruct):
    name: _typing.Final[builtins.str] = ...
    fields: _typing.Final[_typing.Sequence[_fbthrift_ThriftField]] = ...
    is_union: _typing.Final[builtins.bool] = ...
    structured_annotations: _typing.Final[_typing.Sequence[_fbthrift_ThriftConstStruct]] = ...
    def __init__(
        self, *,
        name: _typing.Optional[builtins.str]=...,
        fields: _typing.Optional[_typing.Sequence[_fbthrift_ThriftField]]=...,
        is_union: _typing.Optional[builtins.bool]=...,
        structured_annotations: _typing.Optional[_typing.Sequence[_fbthrift_ThriftConstStruct]]=...
    ) -> None: no_effects()

    def __call__(
        self, *,
        name: _typing.Optional[builtins.str]=...,
        fields: _typing.Optional[_typing.Sequence[_fbthrift_ThriftField]]=...,
        is_union: _typing.Optional[builtins.bool]=...,
        structured_annotations: _typing.Optional[_typing.Sequence[_fbthrift_ThriftConstStruct]]=...
    ) -> _typing.Self: ...
    def __iter__(self) -> _typing.Iterator[_typing.Tuple[builtins.str, _typing.Union[builtins.str, _typing.Sequence[_fbthrift_ThriftField], builtins.bool, _typing.Sequence[_fbthrift_ThriftConstStruct]]]]: ...
    def _to_python(self) -> _typing.Self: ...
    def _to_mutable_python(self) -> "apache.thrift.metadata.thrift_mutable_types.ThriftStruct": ...  # type: ignore
    def _to_py3(self) -> "apache.thrift.metadata.types.ThriftStruct": ...  # type: ignore
    def _to_py_deprecated(self) -> "apache.thrift.metadata.ttypes.ThriftStruct": ...  # type: ignore
_fbthrift_ThriftStruct = ThriftStruct

@_typing.final
class ThriftException(_fbthrift_python_types.Struct, _fbthrift_python_abstract_types.ThriftException):
    name: _typing.Final[builtins.str] = ...
    fields: _typing.Final[_typing.Sequence[_fbthrift_ThriftField]] = ...
    structured_annotations: _typing.Final[_typing.Sequence[_fbthrift_ThriftConstStruct]] = ...
    def __init__(
        self, *,
        name: _typing.Optional[builtins.str]=...,
        fields: _typing.Optional[_typing.Sequence[_fbthrift_ThriftField]]=...,
        structured_annotations: _typing.Optional[_typing.Sequence[_fbthrift_ThriftConstStruct]]=...
    ) -> None: ...

    def __call__(
        self, *,
        name: _typing.Optional[builtins.str]=...,
        fields: _typing.Optional[_typing.Sequence[_fbthrift_ThriftField]]=...,
        structured_annotations: _typing.Optional[_typing.Sequence[_fbthrift_ThriftConstStruct]]=...
    ) -> _typing.Self: ...
    def __iter__(self) -> _typing.Iterator[_typing.Tuple[builtins.str, _typing.Union[builtins.str, _typing.Sequence[_fbthrift_ThriftField], _typing.Sequence[_fbthrift_ThriftConstStruct]]]]: ...
    def _to_python(self) -> _typing.Self: ...
    def _to_mutable_python(self) -> "apache.thrift.metadata.thrift_mutable_types.ThriftException": ...  # type: ignore
    def _to_py3(self) -> "apache.thrift.metadata.types.ThriftException": ...  # type: ignore
    def _to_py_deprecated(self) -> "apache.thrift.metadata.ttypes.ThriftException": ...  # type: ignore
_fbthrift_ThriftException = ThriftException

@_typing.final
class ThriftFunction(_fbthrift_python_types.Struct, _fbthrift_python_abstract_types.ThriftFunction):
    name: _typing.Final[builtins.str] = ...
    return_type: _typing.Final[_fbthrift_ThriftType] = ...
    arguments: _typing.Final[_typing.Sequence[_fbthrift_ThriftField]] = ...
    exceptions: _typing.Final[_typing.Sequence[_fbthrift_ThriftField]] = ...
    is_oneway: _typing.Final[builtins.bool] = ...
    structured_annotations: _typing.Final[_typing.Sequence[_fbthrift_ThriftConstStruct]] = ...
    def __init__(
        self, *,
        name: _typing.Optional[builtins.str]=...,
        return_type: _typing.Optional[_fbthrift_ThriftType]=...,
        arguments: _typing.Optional[_typing.Sequence[_fbthrift_ThriftField]]=...,
        exceptions: _typing.Optional[_typing.Sequence[_fbthrift_ThriftField]]=...,
        is_oneway: _typing.Optional[builtins.bool]=...,
        structured_annotations: _typing.Optional[_typing.Sequence[_fbthrift_ThriftConstStruct]]=...
    ) -> None: no_effects()

    def __call__(
        self, *,
        name: _typing.Optional[builtins.str]=...,
        return_type: _typing.Optional[_fbthrift_ThriftType]=...,
        arguments: _typing.Optional[_typing.Sequence[_fbthrift_ThriftField]]=...,
        exceptions: _typing.Optional[_typing.Sequence[_fbthrift_ThriftField]]=...,
        is_oneway: _typing.Optional[builtins.bool]=...,
        structured_annotations: _typing.Optional[_typing.Sequence[_fbthrift_ThriftConstStruct]]=...
    ) -> _typing.Self: ...
    def __iter__(self) -> _typing.Iterator[_typing.Tuple[builtins.str, _typing.Union[builtins.str, _fbthrift_ThriftType, _typing.Sequence[_fbthrift_ThriftField], _typing.Sequence[_fbthrift_ThriftField], builtins.bool, _typing.Sequence[_fbthrift_ThriftConstStruct]]]]: ...
    def _to_python(self) -> _typing.Self: ...
    def _to_mutable_python(self) -> "apache.thrift.metadata.thrift_mutable_types.ThriftFunction": ...  # type: ignore
    def _to_py3(self) -> "apache.thrift.metadata.types.ThriftFunction": ...  # type: ignore
    def _to_py_deprecated(self) -> "apache.thrift.metadata.ttypes.ThriftFunction": ...  # type: ignore
_fbthrift_ThriftFunction = ThriftFunction

@_typing.final
class ThriftService(_fbthrift_python_types.Struct, _fbthrift_python_abstract_types.ThriftService):
    name: _typing.Final[builtins.str] = ...
    functions: _typing.Final[_typing.Sequence[_fbthrift_ThriftFunction]] = ...
    parent: _typing.Final[_typing.Optional[builtins.str]] = ...
    structured_annotations: _typing.Final[_typing.Sequence[_fbthrift_ThriftConstStruct]] = ...
    uri: _typing.Final[builtins.str] = ...
    def __init__(
        self, *,
        name: _typing.Optional[builtins.str]=...,
        functions: _typing.Optional[_typing.Sequence[_fbthrift_ThriftFunction]]=...,
        parent: _typing.Optional[builtins.str]=...,
        structured_annotations: _typing.Optional[_typing.Sequence[_fbthrift_ThriftConstStruct]]=...,
        uri: _typing.Optional[builtins.str]=...
    ) -> None: no_effects()

    def __call__(
        self, *,
        name: _typing.Optional[builtins.str]=...,
        functions: _typing.Optional[_typing.Sequence[_fbthrift_ThriftFunction]]=...,
        parent: _typing.Optional[builtins.str]=...,
        structured_annotations: _typing.Optional[_typing.Sequence[_fbthrift_ThriftConstStruct]]=...,
        uri: _typing.Optional[builtins.str]=...
    ) -> _typing.Self: ...
    def __iter__(self) -> _typing.Iterator[_typing.Tuple[builtins.str, _typing.Union[builtins.str, _typing.Sequence[_fbthrift_ThriftFunction], builtins.str, _typing.Sequence[_fbthrift_ThriftConstStruct], builtins.str]]]: ...
    def _to_python(self) -> _typing.Self: ...
    def _to_mutable_python(self) -> "apache.thrift.metadata.thrift_mutable_types.ThriftService": ...  # type: ignore
    def _to_py3(self) -> "apache.thrift.metadata.types.ThriftService": ...  # type: ignore
    def _to_py_deprecated(self) -> "apache.thrift.metadata.ttypes.ThriftService": ...  # type: ignore
_fbthrift_ThriftService = ThriftService

@_typing.final
class ThriftModuleContext(_fbthrift_python_types.Struct, _fbthrift_python_abstract_types.ThriftModuleContext):
    name: _typing.Final[builtins.str] = ...
    def __init__(
        self, *,
        name: _typing.Optional[builtins.str]=...
    ) -> None: no_effects()

    def __call__(
        self, *,
        name: _typing.Optional[builtins.str]=...
    ) -> _typing.Self: ...
    def __iter__(self) -> _typing.Iterator[_typing.Tuple[builtins.str, _typing.Union[builtins.str]]]: ...
    def _to_python(self) -> _typing.Self: ...
    def _to_mutable_python(self) -> "apache.thrift.metadata.thrift_mutable_types.ThriftModuleContext": ...  # type: ignore
    def _to_py3(self) -> "apache.thrift.metadata.types.ThriftModuleContext": ...  # type: ignore
    def _to_py_deprecated(self) -> "apache.thrift.metadata.ttypes.ThriftModuleContext": ...  # type: ignore
_fbthrift_ThriftModuleContext = ThriftModuleContext

@_typing.final
class ThriftServiceContext(_fbthrift_python_types.Struct, _fbthrift_python_abstract_types.ThriftServiceContext):
    service_info: _typing.Final[_fbthrift_ThriftService] = ...
    module: _typing.Final[_fbthrift_ThriftModuleContext] = ...
    def __init__(
        self, *,
        service_info: _typing.Optional[_fbthrift_ThriftService]=...,
        module: _typing.Optional[_fbthrift_ThriftModuleContext]=...
    ) -> None: no_effects()

    def __call__(
        self, *,
        service_info: _typing.Optional[_fbthrift_ThriftService]=...,
        module: _typing.Optional[_fbthrift_ThriftModuleContext]=...
    ) -> _typing.Self: ...
    def __iter__(self) -> _typing.Iterator[_typing.Tuple[builtins.str, _typing.Union[_fbthrift_ThriftService, _fbthrift_ThriftModuleContext]]]: ...
    def _to_python(self) -> _typing.Self: ...
    def _to_mutable_python(self) -> "apache.thrift.metadata.thrift_mutable_types.ThriftServiceContext": ...  # type: ignore
    def _to_py3(self) -> "apache.thrift.metadata.types.ThriftServiceContext": ...  # type: ignore
    def _to_py_deprecated(self) -> "apache.thrift.metadata.ttypes.ThriftServiceContext": ...  # type: ignore
_fbthrift_ThriftServiceContext = ThriftServiceContext

@_typing.final
class ThriftServiceContextRef(_fbthrift_python_types.Struct, _fbthrift_python_abstract_types.ThriftServiceContextRef):
    service_name: _typing.Final[builtins.str] = ...
    module: _typing.Final[_fbthrift_ThriftModuleContext] = ...
    def __init__(
        self, *,
        service_name: _typing.Optional[builtins.str]=...,
        module: _typing.Optional[_fbthrift_ThriftModuleContext]=...
    ) -> None: no_effects()

    def __call__(
        self, *,
        service_name: _typing.Optional[builtins.str]=...,
        module: _typing.Optional[_fbthrift_ThriftModuleContext]=...
    ) -> _typing.Self: ...
    def __iter__(self) -> _typing.Iterator[_typing.Tuple[builtins.str, _typing.Union[builtins.str, _fbthrift_ThriftModuleContext]]]: ...
    def _to_python(self) -> _typing.Self: ...
    def _to_mutable_python(self) -> "apache.thrift.metadata.thrift_mutable_types.ThriftServiceContextRef": ...  # type: ignore
    def _to_py3(self) -> "apache.thrift.metadata.types.ThriftServiceContextRef": ...  # type: ignore
    def _to_py_deprecated(self) -> "apache.thrift.metadata.ttypes.ThriftServiceContextRef": ...  # type: ignore
_fbthrift_ThriftServiceContextRef = ThriftServiceContextRef

@_typing.final
class ThriftServiceMetadataResponse(_fbthrift_python_types.Struct, _fbthrift_python_abstract_types.ThriftServiceMetadataResponse):
    context: _typing.Final[_fbthrift_ThriftServiceContext] = ...
    metadata: _typing.Final[_fbthrift_ThriftMetadata] = ...
    services: _typing.Final[_typing.Sequence[_fbthrift_ThriftServiceContextRef]] = ...
    def __init__(
        self, *,
        context: _typing.Optional[_fbthrift_ThriftServiceContext]=...,
        metadata: _typing.Optional[_fbthrift_ThriftMetadata]=...,
        services: _typing.Optional[_typing.Sequence[_fbthrift_ThriftServiceContextRef]]=...
    ) -> None: no_effects()

    def __call__(
        self, *,
        context: _typing.Optional[_fbthrift_ThriftServiceContext]=...,
        metadata: _typing.Optional[_fbthrift_ThriftMetadata]=...,
        services: _typing.Optional[_typing.Sequence[_fbthrift_ThriftServiceContextRef]]=...
    ) -> _typing.Self: ...
    def __iter__(self) -> _typing.Iterator[_typing.Tuple[builtins.str, _typing.Union[_fbthrift_ThriftServiceContext, _fbthrift_ThriftMetadata, _typing.Sequence[_fbthrift_ThriftServiceContextRef]]]]: ...
    def _to_python(self) -> _typing.Self: ...
    def _to_mutable_python(self) -> "apache.thrift.metadata.thrift_mutable_types.ThriftServiceMetadataResponse": ...  # type: ignore
    def _to_py3(self) -> "apache.thrift.metadata.types.ThriftServiceMetadataResponse": ...  # type: ignore
    def _to_py_deprecated(self) -> "apache.thrift.metadata.ttypes.ThriftServiceMetadataResponse": ...  # type: ignore
_fbthrift_ThriftServiceMetadataResponse = ThriftServiceMetadataResponse

@_typing.final
class ThriftMetadata(_fbthrift_python_types.Struct, _fbthrift_python_abstract_types.ThriftMetadata):
    enums: _typing.Final[_typing.Mapping[builtins.str, _fbthrift_ThriftEnum]] = ...
    structs: _typing.Final[_typing.Mapping[builtins.str, _fbthrift_ThriftStruct]] = ...
    exceptions: _typing.Final[_typing.Mapping[builtins.str, _fbthrift_ThriftException]] = ...
    services: _typing.Final[_typing.Mapping[builtins.str, _fbthrift_ThriftService]] = ...
    def __init__(
        self, *,
        enums: _typing.Optional[_typing.Mapping[builtins.str, _fbthrift_ThriftEnum]]=...,
        structs: _typing.Optional[_typing.Mapping[builtins.str, _fbthrift_ThriftStruct]]=...,
        exceptions: _typing.Optional[_typing.Mapping[builtins.str, _fbthrift_ThriftException]]=...,
        services: _typing.Optional[_typing.Mapping[builtins.str, _fbthrift_ThriftService]]=...
    ) -> None: no_effects()

    def __call__(
        self, *,
        enums: _typing.Optional[_typing.Mapping[builtins.str, _fbthrift_ThriftEnum]]=...,
        structs: _typing.Optional[_typing.Mapping[builtins.str, _fbthrift_ThriftStruct]]=...,
        exceptions: _typing.Optional[_typing.Mapping[builtins.str, _fbthrift_ThriftException]]=...,
        services: _typing.Optional[_typing.Mapping[builtins.str, _fbthrift_ThriftService]]=...
    ) -> _typing.Self: ...
    def __iter__(self) -> _typing.Iterator[_typing.Tuple[builtins.str, _typing.Union[_typing.Mapping[builtins.str, _fbthrift_ThriftEnum], _typing.Mapping[builtins.str, _fbthrift_ThriftStruct], _typing.Mapping[builtins.str, _fbthrift_ThriftException], _typing.Mapping[builtins.str, _fbthrift_ThriftService]]]]: ...
    def _to_python(self) -> _typing.Self: ...
    def _to_mutable_python(self) -> "apache.thrift.metadata.thrift_mutable_types.ThriftMetadata": ...  # type: ignore
    def _to_py3(self) -> "apache.thrift.metadata.types.ThriftMetadata": ...  # type: ignore
    def _to_py_deprecated(self) -> "apache.thrift.metadata.ttypes.ThriftMetadata": ...  # type: ignore
_fbthrift_ThriftMetadata = ThriftMetadata


class _fbthrift_ThriftMetadataService_getThriftServiceMetadata_args(_fbthrift_python_types.Struct):

    def __init__(
        self,
    ) -> None: no_effects()

    def __iter__(self) -> _typing.Iterator[_typing.Tuple[
        str,
        _typing.Union[None]]]: ...


class _fbthrift_ThriftMetadataService_getThriftServiceMetadata_result(_fbthrift_python_types.Struct):
    success: _typing.Final[_fbthrift_ThriftServiceMetadataResponse]

    def __init__(
        self, *, success: _typing.Optional[_fbthrift_ThriftServiceMetadataResponse] = ...
    ) -> None: no_effects()

    def __iter__(self) -> _typing.Iterator[_typing.Tuple[
        str,
        _typing.Union[
            _fbthrift_ThriftServiceMetadataResponse,
        ]]]: ...
